version: '3.8'

services:
  mongo:
    image: mongo:6.0.4
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: tarefas
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    image: lucassa1/tarefas_front-main
    container_name: frontend
    environment:
      - REACT_APP_URL_BACKEND=http://backend:5000/produtos
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    image: lucassa1/tarefas_back-main
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/tarefas
    depends_on:
      - mongo

volumes:
  mongo_data: