apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarefas-back-deploy
  labels:
    name: tarefas-back-deploy
    app: tarefas-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tarefas-back-pod
      app: tarefas-app
  template:
    metadata:
      name: tarefas-back-pod
      labels:
        name: tarefas-back-pod
        app: tarefas-app
    spec:
      containers:
        - name: backend
          image: lucassa1/tarefas_back-main
          ports: 
            - containerPort: 8080
          env:
            - name: DATABASE_HOST
              value: "db"
            - name: DATABASE_NAME
              value: "tarefas"